# 开源， 数据计算扩展，ndarray，多维操作，线性代数
> 官网 www.numpy.org

#### ndarray.ndim
数组的轴（维度）的个数。在Python世界中，维度的数量被称为rank。
#### ndarray.shape
数组的维度。这是一个整数的元组，表示每个维度中数组的大小。对于具有n行和m列的矩阵，shape将是(n,m)。因此，shape元组的长度就是rank或维度的个数ndim。
#### ndarray.size
数组元素的总数。这等于shape的元素的乘积。
#### ndarray.dtype
描述数组中元素类型的对象。可以使用标准Python类型创建或指定dtype。另外NumPy提供了自己的类型。例如numpy.int32、numpy.int16和numpy.float64。
#### ndarray.itemsize
数组中每个元素的字节大小。例如，元素为float64类型的数组的itemsize为8（=64/8），而complex32类型的数组的comitemsize为4（=32/8）。它等于ndarray.dtype.itemsize。
#### ndarray.data
该缓冲区包含数组的实际元素。通常，我们不需要使用此属性，因为我们将使用索引访问数组中的元素。

In [22]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
type(a)
#print(a.itemsize)
print(a.ndim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


numpy.ndarray

2


### 将列表转变为ndarray()，数据类型由原列表推倒而来

In [27]:
import numpy as np
np.array([1,2])

array([1, 2])

### 将元组转变为ndarray() 数据类型可由dtype指定

In [50]:
import numpy as np

a=(1,22,233)
np.array(a,dtype=complex)

array([   1.+0.j,   22.+0.j,  233.+0.j])

In [3]:
import numpy as np
#生成一个三维的数组，每个维的长度（秩）为4 数组元素初始为0
a=np.zeros((3,4))
print(a)
#初始为
b=np.ones((2,3),dtype=int)
print(b)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1]
 [1 1 1]]
