### 列表

In [3]:
import numpy as np
lst=[[1,2,4],[2,3,4]]
print(type(lst))
np_lst=np.array(lst)
print(type(np_lst))
### 数据类型有 bool int  int8  int16 int32 int64 int128 uint8 uint16  uint 32
### uint64 uint128 float float16/32 
np_lst=np.array(lst,dtype=np.float)
print(np_lst.shape)
print(np_lst.ndim)
print(np_lst.dtype)
print(np_lst.itemsize)
print(np_lst.size)

<class 'list'>
<class 'numpy.ndarray'>
(2, 3)
2
float64
8
6


In [26]:
print(np.zeros([2,3],dtype=np.bool))
print(np.ones([2,3]))
print(np.random.rand(2,3))
#print(np.random.randint(2,3,3))
print(np.random.randn(2,4))
print(np.random.choice([10,23,133,333]))

[[False False False]
 [False False False]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.10029621  0.53286125  0.19730872]
 [ 0.13604212  0.10110807  0.38361104]]
[[-1.04377564  0.91214243  0.13395697  1.29404972]
 [ 0.44527441  0.4700386  -0.0889599  -1.43275597]]
23
